# Generated by Django 2.2 on 2021-05-21 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('nature_of_experiment', models.CharField(choices=[('Whole Genome Sequencing', 'Whole Genome Sequencing'), ('Metagenomics', 'Metagenomics'), ('Metatranscriptomics', 'Metatranscriptomics'), ('Transcriptomics (RNA Sequencing)', 'Transcriptomics (RNA Sequencing)'), ('Whole Exome Sequencing', 'Whole Exome Sequencing'), ('Small and long RNA sequencing', 'Small and long RNA sequencing'), ('Epigenetics', 'Epigenetics')], max_length=100)),
                ('dna_source', models.CharField(choices=[('Bacteria', 'Bacteria'), ('Human', 'Human'), ('Animals', 'Animals'), ('Plants', 'Plants'), ('Others', 'Others')], max_length=50)),
                ('dna_source_others', models.CharField(blank=True, max_length=100, null=True)),
                ('ipaddress', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
