# Generated by Django 2.2 on 2021-05-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210318_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='affiliation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='industry',
            field=models.CharField(choices=[('Academia', 'Academia'), ('Hospitals', 'Hospitals'), ('Diagnostic Laboratory', 'Diagnostic Laboratory'), ('Clinicians', 'Clinicians'), ('Pharmaceutical Company', 'Pharmaceutical Company'), ('Biotech Company', 'Biotech Company'), ('Genomics Company', 'Genomics Company'), ('Consumer Company', 'Consumer Company')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(choices=[('Dr.', 'Dr.'), ('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Ms.', 'Ms.')], max_length=10, null=True),
        ),
    ]
