# Generated by Django 2.2 on 2021-04-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=9, unique=True)),
                ('sample_sub_attempts', models.IntegerField(default=0)),
                ('company_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=254)),
                ('project_name', models.CharField(max_length=500)),
                ('project_use', models.CharField(max_length=30)),
                ('study_nature', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('project_objective', models.TextField()),
                ('project_outcome', models.TextField()),
                ('service_choice', models.CharField(max_length=40)),
                ('specific_service', models.CharField(max_length=100)),
                ('customized_service', models.TextField()),
                ('ngs_platform', models.CharField(max_length=50)),
                ('ngs_specify', models.CharField(max_length=100)),
                ('model_type', models.CharField(max_length=100)),
                ('sample_type', models.CharField(max_length=30)),
                ('sample_type_specify', models.CharField(max_length=100)),
                ('prepared_library', models.CharField(max_length=500)),
                ('sample_number', models.CharField(max_length=10)),
                ('sequencing_parameter', models.CharField(max_length=40)),
                ('sequencing_other', models.CharField(max_length=100)),
                ('sequencing_depth', models.CharField(max_length=50)),
                ('expected_data', models.CharField(max_length=20)),
                ('expected_data_specify', models.CharField(max_length=100)),
                ('reference_genome', models.CharField(max_length=500)),
                ('data_analysis', models.CharField(max_length=100)),
                ('data_analysis_specify', models.CharField(max_length=100)),
                ('data_delivery', models.CharField(max_length=40)),
                ('data_stored', models.CharField(max_length=10)),
                ('comments', models.TextField()),
                ('hear_us', models.CharField(max_length=30)),
                ('hear_us_specify', models.CharField(max_length=100)),
            ],
        ),
    ]
